#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

try:
    from docx import Document
    from docx.enum.section import WD_SECTION
    from docx.enum.table import WD_ALIGN_VERTICAL, WD_TABLE_ALIGNMENT
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn
    from docx.shared import Inches, Pt, RGBColor
except ModuleNotFoundError as exc:  # pragma: no cover - environment guard
    raise SystemExit(
        "python-docx is required. Use the bundled Codex runtime Python if the "
        "system Python lacks it."
    ) from exc


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = "outputs/submission/project_book_full_zh.md"
DEFAULT_OUTPUT = "outputs/submission/SketchSkill-AKG项目书完整版.docx"
CONTENT_WIDTH_DXA = 9360

BLUE = RGBColor(47, 92, 143)
DARK_BLUE = RGBColor(30, 66, 103)
BLACK = RGBColor(0, 0, 0)
MUTED = RGBColor(90, 90, 90)
TABLE_HEADER_FILL = "F4F6F9"
TABLE_LABEL_FILL = "F2F2F2"
CODE_FILL = "F4F6F9"
BORDER = "D9E1EA"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build the SketchSkill-AKG Chinese project book DOCX."
    )
    parser.add_argument(
        "--source",
        default=DEFAULT_SOURCE,
        help="Standalone Markdown source, usually generated by export_project_book.py.",
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT,
        help="Output DOCX path.",
    )
    args = parser.parse_args()

    source = _resolve(args.source)
    output = _resolve(args.output)
    if not source.exists():
        raise FileNotFoundError(f"Markdown source is missing: {source}")

    doc = Document()
    _configure_document(doc)
    _render_markdown(doc, source.read_text(encoding="utf-8"))

    output.parent.mkdir(parents=True, exist_ok=True)
    doc.save(output)
    _write_metadata(output, source)
    print(f"Exported DOCX: {_display_path(output)}")
    return 0


def _configure_document(doc: Document) -> None:
    section = doc.sections[0]
    section.page_width = Inches(8.5)
    section.page_height = Inches(11)
    section.top_margin = Inches(1)
    section.bottom_margin = Inches(1)
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)
    section.header_distance = Inches(0.492)
    section.footer_distance = Inches(0.492)
    section.different_first_page_header_footer = True

    _set_style_font(doc.styles["Normal"], "Calibri", "Songti SC", 11, BLACK)
    normal = doc.styles["Normal"].paragraph_format
    normal.space_before = Pt(0)
    normal.space_after = Pt(8)
    normal.line_spacing = 1.333
    normal.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY

    for name, size, color, before, after in [
        ("Heading 1", 16, BLUE, 18, 10),
        ("Heading 2", 13, BLUE, 12, 6),
        ("Heading 3", 12, DARK_BLUE, 8, 4),
    ]:
        style = doc.styles[name]
        _set_style_font(style, "Calibri", "Heiti SC", size, color, bold=True)
        pf = style.paragraph_format
        pf.space_before = Pt(before)
        pf.space_after = Pt(after)
        pf.line_spacing = 1.25
        pf.keep_with_next = True

    for style_name in ["List Bullet", "List Number"]:
        style = doc.styles[style_name]
        _set_style_font(style, "Calibri", "Songti SC", 10.5, BLACK)
        pf = style.paragraph_format
        pf.left_indent = Inches(0.375)
        pf.first_line_indent = Inches(-0.194)
        pf.space_after = Pt(4)
        pf.line_spacing = 1.208

    footer = section.footer.paragraphs[0]
    _populate_footer(footer)
    first_footer = section.first_page_footer.paragraphs[0]
    _populate_footer(first_footer)

    header = section.header.paragraphs[0]
    header.alignment = WD_ALIGN_PARAGRAPH.CENTER
    header.paragraph_format.space_after = Pt(0)
    run = header.add_run("SketchSkill-AKG 项目书完整版")
    _set_run_font(run, "Calibri", "Songti SC", 9, MUTED)


def _populate_footer(footer) -> None:
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.paragraph_format.space_before = Pt(0)
    footer.paragraph_format.space_after = Pt(0)
    run = footer.add_run("SketchSkill-AKG 项目书完整版 · 第 ")
    _set_run_font(run, "Calibri", "Songti SC", 9, MUTED)
    _add_field(footer, "PAGE")
    run = footer.add_run(" 页")
    _set_run_font(run, "Calibri", "Songti SC", 9, MUTED)


def _render_markdown(doc: Document, text: str) -> None:
    lines = text.splitlines()
    i = 0
    seen_title = False
    subtitle_pending = False
    front_matter_break_done = False
    paragraph_buffer: list[str] = []

    def flush_paragraph() -> None:
        nonlocal paragraph_buffer, subtitle_pending
        if not paragraph_buffer:
            return
        paragraph = " ".join(part.strip() for part in paragraph_buffer if part.strip())
        paragraph_buffer = []
        if not paragraph:
            return
        if subtitle_pending:
            _add_subtitle(doc, paragraph)
            subtitle_pending = False
            return
        _add_body_paragraph(doc, paragraph)

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            flush_paragraph()
            i += 1
            continue

        if stripped.startswith("```"):
            flush_paragraph()
            fence = stripped[:3]
            code_lines: list[str] = []
            i += 1
            while i < len(lines) and not lines[i].strip().startswith(fence):
                code_lines.append(lines[i])
                i += 1
            _add_code_block(doc, "\n".join(code_lines))
            i += 1
            continue

        heading = re.match(r"^(#{1,6})\s+(.+)$", stripped)
        if heading:
            flush_paragraph()
            level = len(heading.group(1))
            title = _strip_inline_markup(heading.group(2))
            if not seen_title and level == 1:
                _add_cover_title(doc, title)
                seen_title = True
                subtitle_pending = True
            elif level == 1:
                _add_heading(doc, title, 1, page_break_before=title.startswith("附录"))
            else:
                page_break_before = title.startswith("一、") and not front_matter_break_done
                if page_break_before:
                    front_matter_break_done = True
                _add_heading(doc, title, max(1, min(level - 1, 3)), page_break_before=page_break_before)
            i += 1
            continue

        if _is_table_start(lines, i):
            flush_paragraph()
            table_lines: list[str] = []
            while i < len(lines) and _is_table_row(lines[i]):
                table_lines.append(lines[i].strip())
                i += 1
            _add_markdown_table(doc, table_lines)
            continue

        if stripped.startswith("- "):
            flush_paragraph()
            while i < len(lines) and lines[i].strip().startswith("- "):
                item = lines[i].strip()[2:].strip()
                _add_list_item(doc, item, numbered=False)
                i += 1
            continue

        numbered = re.match(r"^\d+\.\s+(.+)$", stripped)
        if numbered:
            flush_paragraph()
            while i < len(lines):
                match = re.match(r"^\d+\.\s+(.+)$", lines[i].strip())
                if not match:
                    break
                _add_list_item(doc, match.group(1).strip(), numbered=True)
                i += 1
            continue

        paragraph_buffer.append(stripped)
        i += 1

    flush_paragraph()


def _add_cover_title(doc: Document, title: str) -> None:
    kicker = doc.add_paragraph()
    kicker.alignment = WD_ALIGN_PARAGRAPH.CENTER
    kicker.paragraph_format.space_after = Pt(12)
    run = kicker.add_run("SketchSkill-AKG 项目书完整版")
    _set_run_font(run, "Calibri", "Songti SC", 10.5, BLACK)

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before = Pt(8)
    p.paragraph_format.space_after = Pt(18)
    display_title = "项目书完整版" if "项目书完整版" in title else title
    run = p.add_run(display_title)
    _set_run_font(run, "Calibri", "Heiti SC", 24, BLACK, bold=True)


def _add_subtitle(doc: Document, text: str) -> None:
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_after = Pt(22)
    run = p.add_run(_strip_inline_markup(text))
    _set_run_font(run, "Calibri", "Heiti SC", 15, BLACK, bold=True)


def _add_heading(doc: Document, text: str, level: int, *, page_break_before: bool = False) -> None:
    p = doc.add_heading("", level=level)
    if page_break_before:
        p.paragraph_format.page_break_before = True
    _append_inline_runs(p, text, heading=True)


def _add_body_paragraph(doc: Document, text: str) -> None:
    p = doc.add_paragraph()
    p.paragraph_format.first_line_indent = Inches(0.28)
    p.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    _append_inline_runs(p, text)


def _add_list_item(doc: Document, text: str, *, numbered: bool) -> None:
    p = doc.add_paragraph(style="List Number" if numbered else "List Bullet")
    p.paragraph_format.first_line_indent = Inches(-0.194)
    _append_inline_runs(p, text)


def _add_code_block(doc: Document, code: str) -> None:
    lines = code.splitlines() or [""]
    for index, line in enumerate(lines):
        p = doc.add_paragraph()
        p.paragraph_format.left_indent = Inches(0.15)
        p.paragraph_format.right_indent = Inches(0.05)
        p.paragraph_format.space_before = Pt(3 if index == 0 else 0)
        p.paragraph_format.space_after = Pt(8 if index == len(lines) - 1 else 0)
        p.paragraph_format.line_spacing = 1.0
        _set_paragraph_shading(p, CODE_FILL)
        run = p.add_run(line if line else " ")
        _set_run_font(run, "Menlo", "Menlo", 8.5, RGBColor(35, 39, 47))


def _add_markdown_table(doc: Document, table_lines: list[str]) -> None:
    rows = [_parse_table_row(line) for line in table_lines]
    rows = [row for row in rows if row and not _is_separator_row(row)]
    if not rows:
        return

    column_count = max(len(row) for row in rows)
    rows = [row + [""] * (column_count - len(row)) for row in rows]
    widths = _column_widths(rows)
    table = doc.add_table(rows=len(rows), cols=column_count)
    table.alignment = WD_TABLE_ALIGNMENT.LEFT
    table.autofit = False
    _set_table_geometry(table, widths)
    _set_table_borders(table)

    for r_idx, row in enumerate(rows):
        for c_idx, value in enumerate(row):
            cell = table.cell(r_idx, c_idx)
            cell.vertical_alignment = WD_ALIGN_VERTICAL.CENTER
            _set_cell_margins(cell, top=80, bottom=80, start=120, end=120)
            _set_cell_width(cell, widths[c_idx])
            if r_idx == 0:
                _set_cell_shading(cell, TABLE_HEADER_FILL)
            elif column_count == 2 and c_idx == 0:
                _set_cell_shading(cell, TABLE_LABEL_FILL)
            p = cell.paragraphs[0]
            p.paragraph_format.space_before = Pt(0)
            p.paragraph_format.space_after = Pt(0)
            p.paragraph_format.line_spacing = 1.15
            if c_idx > 0 and _looks_short_value(value):
                p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            _append_inline_runs(p, value, table_cell=True, bold=(r_idx == 0 or (column_count == 2 and c_idx == 0)))

    after = doc.add_paragraph()
    after.paragraph_format.space_after = Pt(4)


def _append_inline_runs(
    paragraph,
    text: str,
    *,
    heading: bool = False,
    table_cell: bool = False,
    bold: bool = False,
) -> None:
    text = _normalize_inline_links(text)
    parts = re.split(r"(`[^`]+`|\*\*[^*]+\*\*)", text)
    for part in parts:
        if not part:
            continue
        is_code = part.startswith("`") and part.endswith("`")
        is_bold = part.startswith("**") and part.endswith("**")
        clean = part[1:-1] if is_code else part[2:-2] if is_bold else part
        run = paragraph.add_run(clean)
        size = 10 if table_cell else None
        font = "Menlo" if is_code else "Calibri"
        east_asia = "Menlo" if is_code else ("Heiti SC" if heading else "Songti SC")
        color = DARK_BLUE if heading else BLACK
        _set_run_font(run, font, east_asia, size, color, bold=(bold or is_bold or heading))
        if is_code:
            run.font.size = Pt(9 if not table_cell else 8.5)


def _is_table_start(lines: list[str], index: int) -> bool:
    return (
        index + 1 < len(lines)
        and _is_table_row(lines[index].strip())
        and _is_separator_line(lines[index + 1].strip())
    )


def _is_table_row(line: str) -> bool:
    return line.strip().startswith("|") and line.strip().endswith("|")


def _is_separator_line(line: str) -> bool:
    if not _is_table_row(line):
        return False
    cells = _parse_table_row(line)
    return bool(cells) and all(re.fullmatch(r":?-{3,}:?", cell.strip()) for cell in cells)


def _is_separator_row(row: Iterable[str]) -> bool:
    return all(re.fullmatch(r":?-{3,}:?", cell.strip()) for cell in row)


def _parse_table_row(line: str) -> list[str]:
    text = line.strip()
    if text.startswith("|"):
        text = text[1:]
    if text.endswith("|"):
        text = text[:-1]
    return [_strip_inline_markup(cell.strip()) for cell in text.split("|")]


def _column_widths(rows: list[list[str]]) -> list[int]:
    count = len(rows[0])
    weights: list[int] = []
    for col in range(count):
        values = [row[col] for row in rows]
        max_len = max((_display_len(value) for value in values), default=1)
        weights.append(max(8, min(max_len, 38)))

    minimum = 900 if count >= 5 else 1100
    widths = [max(minimum, round(CONTENT_WIDTH_DXA * weight / sum(weights))) for weight in weights]
    excess = sum(widths) - CONTENT_WIDTH_DXA
    while excess > 0:
        idx = max(range(count), key=lambda i: widths[i])
        reduction = min(excess, max(0, widths[idx] - minimum))
        if reduction == 0:
            break
        widths[idx] -= reduction
        excess -= reduction
    if sum(widths) != CONTENT_WIDTH_DXA:
        widths[-1] += CONTENT_WIDTH_DXA - sum(widths)
    return widths


def _display_len(text: str) -> int:
    total = 0
    for char in text:
        total += 2 if ord(char) > 127 else 1
    return total


def _looks_short_value(value: str) -> bool:
    return _display_len(value) <= 18 or bool(re.fullmatch(r"[0-9.`x%/-]+", value.strip()))


def _strip_inline_markup(text: str) -> str:
    text = _normalize_inline_links(text)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    return text


def _normalize_inline_links(text: str) -> str:
    return re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r"\1（\2）", text)


def _set_style_font(style, latin: str, east_asia: str, size: float, color: RGBColor, bold: bool = False) -> None:
    font = style.font
    font.name = latin
    font.size = Pt(size)
    font.color.rgb = color
    font.bold = bold
    style.element.rPr.rFonts.set(qn("w:ascii"), latin)
    style.element.rPr.rFonts.set(qn("w:hAnsi"), latin)
    style.element.rPr.rFonts.set(qn("w:eastAsia"), east_asia)


def _set_run_font(
    run,
    latin: str,
    east_asia: str,
    size: float | None,
    color: RGBColor,
    *,
    bold: bool = False,
) -> None:
    run.font.name = latin
    run._element.rPr.rFonts.set(qn("w:ascii"), latin)
    run._element.rPr.rFonts.set(qn("w:hAnsi"), latin)
    run._element.rPr.rFonts.set(qn("w:eastAsia"), east_asia)
    if size is not None:
        run.font.size = Pt(size)
    run.font.color.rgb = color
    run.bold = bold


def _set_table_geometry(table, widths: list[int]) -> None:
    tbl = table._tbl
    tbl_pr = tbl.tblPr
    tbl_w = tbl_pr.find(qn("w:tblW"))
    if tbl_w is None:
        tbl_w = OxmlElement("w:tblW")
        tbl_pr.insert(0, tbl_w)
    tbl_w.set(qn("w:type"), "dxa")
    tbl_w.set(qn("w:w"), str(CONTENT_WIDTH_DXA))

    tbl_ind = OxmlElement("w:tblInd")
    tbl_ind.set(qn("w:w"), "120")
    tbl_ind.set(qn("w:type"), "dxa")
    tbl_pr.append(tbl_ind)

    grid = tbl.tblGrid
    if grid is None:
        grid = OxmlElement("w:tblGrid")
        tbl.insert(1, grid)
    for child in list(grid):
        grid.remove(child)
    for width in widths:
        col = OxmlElement("w:gridCol")
        col.set(qn("w:w"), str(width))
        grid.append(col)


def _set_table_borders(table) -> None:
    tbl_pr = table._tbl.tblPr
    borders = tbl_pr.first_child_found_in("w:tblBorders")
    if borders is None:
        borders = OxmlElement("w:tblBorders")
        tbl_pr.append(borders)
    for edge in ["top", "left", "bottom", "right", "insideH", "insideV"]:
        tag = f"w:{edge}"
        element = borders.find(qn(tag))
        if element is None:
            element = OxmlElement(tag)
            borders.append(element)
        element.set(qn("w:val"), "single")
        element.set(qn("w:sz"), "4")
        element.set(qn("w:space"), "0")
        element.set(qn("w:color"), BORDER)


def _set_cell_width(cell, width: int) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    tc_w = tc_pr.tcW
    if tc_w is None:
        tc_w = OxmlElement("w:tcW")
        tc_pr.append(tc_w)
    tc_w.set(qn("w:w"), str(width))
    tc_w.set(qn("w:type"), "dxa")


def _set_cell_shading(cell, fill: str) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    shading = tc_pr.find(qn("w:shd"))
    if shading is None:
        shading = OxmlElement("w:shd")
        tc_pr.append(shading)
    shading.set(qn("w:fill"), fill)


def _set_cell_margins(cell, *, top: int, bottom: int, start: int, end: int) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    tc_mar = tc_pr.first_child_found_in("w:tcMar")
    if tc_mar is None:
        tc_mar = OxmlElement("w:tcMar")
        tc_pr.append(tc_mar)
    for name, value in [("top", top), ("bottom", bottom), ("start", start), ("end", end)]:
        element = tc_mar.find(qn(f"w:{name}"))
        if element is None:
            element = OxmlElement(f"w:{name}")
            tc_mar.append(element)
        element.set(qn("w:w"), str(value))
        element.set(qn("w:type"), "dxa")


def _set_paragraph_shading(paragraph, fill: str) -> None:
    p_pr = paragraph._p.get_or_add_pPr()
    shading = p_pr.find(qn("w:shd"))
    if shading is None:
        shading = OxmlElement("w:shd")
        p_pr.append(shading)
    shading.set(qn("w:fill"), fill)


def _add_field(paragraph, instruction: str) -> None:
    run = paragraph.add_run()
    fld_begin = OxmlElement("w:fldChar")
    fld_begin.set(qn("w:fldCharType"), "begin")
    run._r.append(fld_begin)

    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = f" {instruction} "
    run._r.append(instr)

    fld_end = OxmlElement("w:fldChar")
    fld_end.set(qn("w:fldCharType"), "end")
    run._r.append(fld_end)


def _write_metadata(output: Path, source: Path) -> None:
    metadata = {
        "output": _display_path(output),
        "source": _display_path(source),
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "style_preset": "narrative_proposal",
        "header_template": "proposal_centerpiece inspired by base Pages/PDF",
    }
    output.with_suffix(output.suffix + ".metadata.json").write_text(
        json.dumps(metadata, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def _resolve(path: str | Path) -> Path:
    value = Path(path)
    if value.is_absolute():
        return value
    return ROOT / value


def _display_path(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


if __name__ == "__main__":
    raise SystemExit(main())
